name: NPM CI

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        required: false
        default: 16
    secrets:
      node_auth_token:
        required: false

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    -
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        registry-url: https://npm.pkg.github.com/
    -
      name: Install dependencies
      run: npm install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.node_auth_token }}
    -
      name: Build
      run: npm run build --if-present
    -
      name: Run tests
      run: npm test
